# Generated by Django 5.0.3 on 2024-03-24 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quality_control", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugreport",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bugs",
                to="tasks.project",
            ),
        ),
        migrations.AlterField(
            model_name="bugreport",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bugs",
                to="tasks.task",
            ),
        ),
    ]
