# Generated by Django 5.0.3 on 2024-04-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quality_control", "0002_alter_bugreport_project_alter_bugreport_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugreport",
            name="priority",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True
            ),
        ),
        migrations.AlterField(
            model_name="featurerequest",
            name="priority",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True
            ),
        ),
    ]
