# Generated by Django 5.0.3 on 2024-04-06 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quality_control", "0003_alter_bugreport_priority_and_more"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugreport",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bugs",
                to="tasks.project",
            ),
        ),
        migrations.AlterField(
            model_name="featurerequest",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="tasks.project",
            ),
        ),
    ]
