# Generated by Django 5.0.3 on 2024-04-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "quality_control",
            "0004_alter_bugreport_project_alter_featurerequest_project",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugreport",
            name="priority",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1
            ),
        ),
        migrations.AlterField(
            model_name="featurerequest",
            name="priority",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1
            ),
        ),
    ]
